### ISSUE TITLE
[Question] Is this capable of multiple user role login for Facebook?

### ISSUE THREAD

**Issue by softnayr** [g0ld3lux/laravel-vue-starter#1]
I have publisher, author, and user roles and I want to have Facebook login for each of those roles? How do I do that using your project? 

Any thoughts?

**Comment by g0ld3lux** [comment]
There Are 2 Ways to Login Via Facebook, 

Clientside Using FBLogin Component , the Other One is The Built In Facebook SDK Login Route i made.

Use Case of ClientSide is if you just need to fetch the User Profile, Bring Extra Permission , or Get Access Token from FB.

Depending On What You Need. If You Dont Need to Access The Database You Can Use Client Side Login, 

If You Need to Touch Your database , and Register the  Their FB Credentials as Well as Sign them up.
And Even Save Fb Access Token , Short or Long Live Token , as Well as their Profiles. You may Need to Use the Api End point Ive Set For FBLoginController.php


You Need To Modify The Sign Up Process...

Either You build a VueJS  SignUp/Login Component that will pass the data for the roles you want

When You Make a Post Request to FBLoginController@authenticate Endpoint. 

The Easiest Thing to do, is Just Log the User as Normal . 

Either using the 2 options stated above or use the main login/signup endpoint .

as you can see i have made a generateUniqueCode method

This Will generate Big Interger  ID number if no Facebook ID was presented During login or Sign Up

and Also if you Passed the FB ID using clientside authentication Then Save it on Your Vuex User Module , then making a post request to the main login or sign up endpoint .

You Can Login a User Fb Id.

So In Total you have 3 Ways To Login Using FB ...

After you SUccessfully log in you can then Create a View/Routes that will be Restricted by Roles or permission.

There is an Example of that already in the routes.php

Please check it out... If you the user that is log in has that roles, automatically he is given acess to that routes...

If You Need help , try to code it first whats in your mind then ill try to check it, then ill make a pull request on your fork on this repo.

**Comment by g0ld3lux** [comment]
Please check the https://github.com/g0ld3lux/laravel-vue-starter/blob/master/Docs/Changelog.md

It has info on all features i implemented here

**Comment by softnayr** [comment]
This is a nice project indeed. I would need to get basic user information from FB user like name, email so that means I can go for the FB SDK login you need. The problem is how would I know if the user is a publisher or author when he registers using FB. I'm going to try your codes and see how it works.

Thanks :)

**Comment by g0ld3lux** [comment]
you have 2 options , you can add it to session the type of roles for that fb account or use cookie.
that way you can get that info on the callback request , you do need to edit the authenticate method on FbloginController.php

**Comment by softnayr** [comment]
thanks for the tip ;)
